---
- name: Mark lihas_sysctl done
  ansible.builtin.set_fact:
    lihas_sysctl_done: true
- name: Include variables
  ansible.builtin.include_role:
    name: lihas_variables
  when: configspaces is not defined

- name: Combine sysctls, init
  ansible.builtin.set_fact:
    lihas_sysctls: {}
- name: Combine sysctls, expand with configspaces
  ansible.builtin.set_fact:
    lihas_sysctls: "{{ lihas_sysctls | combine(hostvars[inventory_hostname][item]['config']['sysctl'] | default({})) }}"
  loop: "{{ configspaces }}"
- name: Debug lihas_sysctls
  ansible.builtin.debug:
    var: lihas_sysctls
    verbosity: 1
- name: Include sysctl
  ansible.builtin.include_tasks: sysctl.yml
  loop: "{{ lihas_sysctls | dict2items() }}"
  loop_control:
    loop_var: sysctl
...
