---
- name: debug sysctl
  debug:
    var: sysctl
    verbosity: 1
- name: "sysctl {{ sysctl.key }}"
  sysctl:
    name: "{{ sysctl.value.ctl }}"
    sysctl_file: "/etc/sysctl.d/{{ sysctl.key }}.conf"
    value: "{{ sysctl.value.value }}"
    sysctl_set: true
    state: present
    reload: true
...
