---
- name: Debug sysctl
  ansible.builtin.debug:
    var: sysctl
    verbosity: 1
- name: "Set sysctl {{ sysctl.key }}"
  ansible.posix.sysctl:
    name: "{{ sysctl.value.ctl }}"
    sysctl_file: "/etc/sysctl.d/{{ sysctl.key }}.conf"
    value: "{{ sysctl.value.value }}"
    sysctl_set: true
    state: present
    reload: true
...
